[package]
name = "Movemate"
version = "1.0.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
std = "0x1"
sui = "0x2"
movemate = "0xdc8a9f1bb748d40e246089e10588909d4850f4a4"

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/deps/move-stdlib"
rev = "cff7a37e5c9b6bba1c82ff184657963a3ddba0e6"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
rev = "cff7a37e5c9b6bba1c82ff184657963a3ddba0e6"
